### ISSUE TITLE
It's not that secure...

### ISSUE THREAD

**Issue by qgustavor** [eykjs/mongocrypt#1]
Summary: ["If You're Typing the Letters A-E-S Into Your Code You're Doing It Wrong"](https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2009/july/if-youre-typing-the-letters-a-e-s-into-your-code-youre-doing-it-wrong/)

From the above, unless you have to support some existent code, it's better to use a tool that make it hard to do the wrong thing. The current implementation use a fixed IV, so if two values are the same the encrypted value are equal. Also it doesn't authenticate the ciphertext, so data can be tampered.

You can use a library which handles crypto for you (like [keyczarjs](https://github.com/mitro-co/keyczarjs)). Or you can keep AES, but it's easier to things get wrong: you can use random IVs, also an authenticated block mode or handle authentication for yourself (using HMAC).

**Comment by eykrehbein** [comment]
Thanks for your issue. To answer it: I know about the issue with the fixed IV. As I started to code, I was working with a random IV but then I realized that I have a problem: while executing `find()`, `findOne()`, `updateOne()` and `updateMany()` the data has to be encrypted before querying because else the query wouldn't work. And that's because the query value gets encrypted aswell before executing query functions. And if it were an AES encryption with random IV, the decrypted values of query and database data were the same but the encrypted versions (**for what is mongodb actually searching**) differ. I'm already working on a solution
